/**
 * Canonical hotel catalog (deduped from partner history).
 * zoneName null = admin must assign (Patong / Kata / Karon only for now).
 */
export type HotelSeed = {
  name: string
  zoneName: 'Patong' | 'Kata' | 'Karon' | null
}

export const HOTEL_CATALOG: HotelSeed[] = [
  // Patong
  { name: 'Absolute Twin Sands Resort & Spa', zoneName: 'Patong' },
  { name: 'Amari Phuket', zoneName: 'Patong' },
  { name: 'Amici Miei Hotel', zoneName: 'Patong' },
  { name: 'Anchor Boutique House', zoneName: 'Patong' },
  { name: 'Andakira Hotel Phuket', zoneName: 'Patong' },
  { name: 'Andaman Beach Hotel Phuket', zoneName: 'Patong' },
  { name: 'Andaman Embrace Patong', zoneName: 'Patong' },
  { name: 'Andamantra Resort and Villa Phuket', zoneName: 'Patong' },
  { name: 'APK Resort Patong', zoneName: 'Patong' },
  { name: 'Ashlee Plaza Patong Hotel & Spa', zoneName: 'Patong' },
  { name: 'Aspery Hotel Phuket', zoneName: 'Patong' },
  { name: 'Avista Hideaway Phuket Patong', zoneName: 'Patong' },
  { name: 'Baan Yuree Resort', zoneName: 'Patong' },
  { name: 'Baramee Resort', zoneName: 'Patong' },
  { name: 'Bauman Casa Beach Resort', zoneName: 'Patong' },
  { name: 'Bauman Residence', zoneName: 'Patong' },
  { name: 'Beachcomber Phuket', zoneName: 'Patong' },
  { name: 'Bel Aire Patong, Phuket', zoneName: 'Patong' },
  { name: 'Belvedere Guest House', zoneName: 'Patong' },
  { name: 'Best Western Patong Beach', zoneName: 'Patong' },
  { name: 'Beyond Patong', zoneName: 'Patong' },
  { name: 'Breezotel', zoneName: 'Patong' },
  { name: 'Burasari Phuket', zoneName: 'Patong' },
  { name: 'Centre Point Hotel Patong Beach', zoneName: 'Patong' },
  { name: 'Citrus Patong Hotel By Compass Hospitality', zoneName: 'Patong' },
  { name: 'Courtyard by Marriott Phuket patong', zoneName: 'Patong' },
  { name: 'Crest Resort & Pool Villas', zoneName: 'Patong' },
  { name: 'Deevana Plaza Phuket', zoneName: 'Patong' },
  { name: 'Deevana Patong Resort & Spa', zoneName: 'Patong' },
  { name: 'Dinso Resort & Villas Phuket', zoneName: 'Patong' },
  { name: 'DoubleTree by Hilton Phuket Banthai Resort', zoneName: 'Patong' },
  { name: 'Duangjitt Resort', zoneName: 'Patong' },
  { name: 'Elite Suites Patong, Phuket', zoneName: 'Patong' },
  { name: "Fishermen's Harbour", zoneName: 'Patong' },
  { name: 'Four Points by Sheraton', zoneName: 'Patong' },
  { name: 'FunDee Boutique Hotel', zoneName: 'Patong' },
  { name: 'GP House Phuket', zoneName: 'Patong' },
  { name: 'Grace Patong Hotel', zoneName: 'Patong' },
  { name: 'Grand Mercure Phuket', zoneName: 'Patong' },
  { name: 'Grand Orchid Inn Hotel', zoneName: 'Patong' },
  { name: 'Grand Tower Inn Patong', zoneName: 'Patong' },
  { name: 'GU HOTEL', zoneName: 'Patong' },
  { name: 'Holiday Inn Express Phuket', zoneName: 'Patong' },
  { name: 'Holiday Inn Resort Phuket', zoneName: 'Patong' },
  { name: 'Homm Bliss Southbeach Patong', zoneName: 'Patong' },
  { name: 'Horizon Patong Beach Resort & Spa', zoneName: 'Patong' },
  { name: 'Hotel Clover Patong Phuket', zoneName: 'Patong' },
  { name: 'Hotel Indigo Phuket Patong by IHG', zoneName: 'Patong' },
  { name: 'Ibis Phuket Patong', zoneName: 'Patong' },
  { name: 'Impiana Resort Patong Phuket', zoneName: 'Patong' },
  { name: 'Kalima Resort and Spa', zoneName: 'Patong' },
  { name: 'Kudo Hotel & Beach Club', zoneName: 'Patong' },
  { name: 'La Flora Resort Patong', zoneName: 'Patong' },
  { name: 'Lub d Phuket Patong', zoneName: 'Patong' },
  { name: 'M Social Phuket', zoneName: 'Patong' },
  { name: 'Malabar Pool Villa Phuket', zoneName: 'Patong' },
  { name: 'Mercure Phuket Patong Journeyhub', zoneName: 'Patong' },
  { name: 'Mövenpick Myth Hotel', zoneName: 'Patong' },
  { name: 'Nap Patong', zoneName: 'Patong' },
  { name: 'Neptuna Hotel', zoneName: 'Patong' },
  { name: 'Nipa Resort Phuket', zoneName: 'Patong' },
  { name: 'Novotel Phuket Vintage Park Resort', zoneName: 'Patong' },
  { name: 'Palmyra Patong Resort Phuket', zoneName: 'Patong' },
  { name: 'Paripas Express Patong', zoneName: 'Patong' },
  { name: 'Patong Backpacker Hostel', zoneName: 'Patong' },
  { name: 'Patong Bay Hill', zoneName: 'Patong' },
  { name: 'Patong Bay Residence', zoneName: 'Patong' },
  { name: 'Patong Beach Hotel', zoneName: 'Patong' },
  { name: 'Patong Hemingways Hotel', zoneName: 'Patong' },
  { name: 'Patong Lodge Hotel', zoneName: 'Patong' },
  { name: 'Patong Max Value Hotel, Patong Beach', zoneName: 'Patong' },
  { name: 'Patong Merlin Hotel', zoneName: 'Patong' },
  { name: 'Patong Paragon Resort', zoneName: 'Patong' },
  { name: 'Patong Pearl Hotel', zoneName: 'Patong' },
  { name: 'Patong Resort', zoneName: 'Patong' },
  { name: 'Patong Signature Boutique Hotel', zoneName: 'Patong' },
  { name: 'Phuket Gazette Resort Patong', zoneName: 'Patong' },
  { name: 'Phuket Graceland Resort and Spa', zoneName: 'Patong' },
  { name: 'Phuket Marriott Resort & Spa, Merlin Beach', zoneName: 'Patong' },
  { name: 'Poppa Palace Hotel', zoneName: 'Patong' },
  { name: 'R-Mar Resort and Spa Patong', zoneName: 'Patong' },
  { name: 'Riders Lodge Phuket', zoneName: 'Patong' },
  { name: 'Rosewood Phuket', zoneName: 'Patong' },
  { name: 'Royal Phawadee Village Hotel', zoneName: 'Patong' },
  { name: 'Safari Beach Hotel', zoneName: 'Patong' },
  { name: 'Sawaddi Patong Resort & Spa', zoneName: 'Patong' },
  { name: 'Seaview Patong Hotel', zoneName: 'Patong' },
  { name: 'Seven Seas Hotel Patong', zoneName: 'Patong' },
  { name: 'Siras Room Patong', zoneName: 'Patong' },
  { name: 'Skyview Resort Phuket Patong Beach', zoneName: 'Patong' },
  { name: 'sleep with me', zoneName: 'Patong' },
  { name: 'Sunshine Patong', zoneName: 'Patong' },
  { name: 'Sunset Beach Resort', zoneName: 'Patong' },
  { name: 'Swissotel Resort Phuket Patong Beach', zoneName: 'Patong' },
  { name: 'The AIM Patong Hotel', zoneName: 'Patong' },
  { name: 'The Album Hotel', zoneName: 'Patong' },
  { name: 'The Ashlee Heights Patong Hotel & Suites', zoneName: 'Patong' },
  { name: 'The Bird Spazzio Hotel', zoneName: 'Patong' },
  { name: 'The Block Hotel', zoneName: 'Patong' },
  { name: 'The Charm Resort Phuket', zoneName: 'Patong' },
  { name: 'The Elegant Patong', zoneName: 'Patong' },
  { name: 'The Kee Resort & Spa', zoneName: 'Patong' },
  { name: 'The Lunar Patong', zoneName: 'Patong' },
  { name: 'The Marina Phuket Hotel', zoneName: 'Patong' },
  { name: 'The Royal Paradise Hotel & Spa', zoneName: 'Patong' },
  { name: 'The Senses Resort & Pool Villas', zoneName: 'Patong' },
  { name: 'The Signature Hotel Patong', zoneName: 'Patong' },
  { name: 'Tiras Patong Beach Hotel', zoneName: 'Patong' },
  { name: 'WOOVO Phuket Patong', zoneName: 'Patong' },
  { name: 'Wyndham Grand Phuket Kalim Bay', zoneName: 'Patong' },
  { name: 'Zenseana Phuket Hotel', zoneName: 'Patong' },
  { name: 'Zostel Phuket Hostel', zoneName: 'Patong' },
  // Kata
  { name: 'Aurico Kata Resort & Spa', zoneName: 'Kata' },
  { name: 'Avista Grande Phuket Karon - MGallery', zoneName: 'Kata' },
  { name: 'Beyond Resort Kata', zoneName: 'Kata' },
  { name: 'Centara Kata Resort Phuket', zoneName: 'Kata' },
  { name: 'Chanalai Flora Resort, Kata Beach', zoneName: 'Kata' },
  { name: 'Chanalai Garden Resort, Kata Beach', zoneName: 'Kata' },
  { name: 'Chanalai Romantica Resort', zoneName: 'Kata' },
  { name: 'Grand Kata VIP - Kata Beach', zoneName: 'Kata' },
  { name: 'Impiana Private Villas Kata Noi', zoneName: 'Kata' },
  { name: 'Kata Palm Resort & Spa', zoneName: 'Kata' },
  { name: 'Kata Rocks Resort & Residences', zoneName: 'Kata' },
  { name: 'Kata Sea Breeze Resort', zoneName: 'Kata' },
  { name: 'Katathani Phuket Beach Resort', zoneName: 'Kata' },
  { name: 'Malisa Villa Resort', zoneName: 'Kata' },
  { name: 'Mandarava Resort & Spa Phuket', zoneName: 'Kata' },
  { name: 'Metadee Concept Hotel', zoneName: 'Kata' },
  { name: 'Metadee Resort & Villas', zoneName: 'Kata' },
  { name: "Mom Tri's Villa Royale", zoneName: 'Kata' },
  { name: 'Must Sea Hotel', zoneName: 'Kata' },
  { name: 'Novotel Phuket Kata Avista', zoneName: 'Kata' },
  { name: 'OZO Phuket', zoneName: 'Kata' },
  { name: 'Pamookkoo Resort', zoneName: 'Kata' },
  { name: 'Sawasdee Village', zoneName: 'Kata' },
  { name: 'Sugar Marina Resort - FASHION - Kata Beach', zoneName: 'Kata' },
  { name: 'Sugar Marina Resort - NAUTICAL - Kata Beach', zoneName: 'Kata' },
  { name: 'Sugar Marina Resort - SURF - Kata Beach', zoneName: 'Kata' },
  { name: 'The Baray Villa by Sawasdee Village', zoneName: 'Kata' },
  { name: 'The Beach Heights Resort', zoneName: 'Kata' },
  { name: 'The Boathouse Phuket', zoneName: 'Kata' },
  { name: 'The Focus Housing Kata', zoneName: 'Kata' },
  { name: 'The Sea Galleri by Katathani', zoneName: 'Kata' },
  { name: 'The Shore at Katathani', zoneName: 'Kata' },
  { name: 'The SIS Kata Resort', zoneName: 'Kata' },
  // Karon
  { name: 'Chanalai Hillside Resort', zoneName: 'Karon' },
  { name: 'Peach Hill Hotel & Resort', zoneName: 'Karon' },
  { name: 'Princess Seaview Resort and Spa', zoneName: 'Karon' },
  { name: 'Thavorn Palm Beach Resort Phuket', zoneName: 'Karon' },
  { name: 'Utopia Karon', zoneName: 'Karon' },
  // Unassigned
  { name: 'La Vista', zoneName: null },
  { name: 'Radisson Resort and Suites Phuket', zoneName: null },
]
