import type { Agent, Availability, Booking, PickupZone } from '@/lib/types'
import { bookingCodeStem } from '@/lib/format'

export const AGENTS: Agent[] = [
  { slug: 'abc-travel', name: 'ABC Travel India', country: 'India', status: 'Active' },
  { slug: 'golden-triangle', name: 'Golden Triangle Travel', country: 'India', status: 'Active' },
  { slug: 'mumbai-holidays', name: 'Mumbai Holidays', country: 'India', status: 'Active' },
  { slug: 'delhi-travel', name: 'Delhi Travel Group', country: 'India', status: 'Active' },
]

export const INITIAL_ZONES: PickupZone[] = [
  { name: 'Patong', time: '07:30', pending: false },
  { name: 'Kata', time: '07:45', pending: false },
  { name: 'Karon', time: '08:00', pending: false },
  { name: 'Other', time: 'Awaiting pickup time', pending: true },
]

/** Realistic day board: mostly couples / singles, a few small groups. */
const SEP17_PP_GUESTS: Array<{
  guest: string
  agent: (typeof AGENTS)[number]
  adults: number
  children?: number
  infants?: number
  zone: PickupZone['name']
  hotel: string
  pending?: boolean
}> = [
  { guest: 'John Smith', agent: AGENTS[0], adults: 2, zone: 'Patong', hotel: 'ABC Hotel' },
  { guest: 'Sanjay Patel', agent: AGENTS[2], adults: 1, zone: 'Karon', hotel: 'Centara Grand' },
  { guest: 'Neha Gupta', agent: AGENTS[3], adults: 2, children: 1, zone: 'Kata', hotel: 'Kata Palm Resort' },
  { guest: 'Arjun Reddy', agent: AGENTS[1], adults: 2, zone: 'Patong', hotel: 'Holiday Inn Resort' },
  { guest: 'Lisa Wong', agent: AGENTS[0], adults: 1, zone: 'Other', hotel: 'The Nai Harn', pending: true },
  { guest: 'Vikram Shah', agent: AGENTS[2], adults: 2, zone: 'Karon', hotel: 'Beyond Resort Karon' },
  { guest: 'Emma Clarke', agent: AGENTS[1], adults: 2, zone: 'Patong', hotel: 'Impiana Patong' },
  { guest: 'Hiro Tanaka', agent: AGENTS[0], adults: 1, zone: 'Kata', hotel: 'Boathouse' },
  { guest: 'Maria Santos', agent: AGENTS[3], adults: 2, zone: 'Karon', hotel: 'Centara Grand' },
  { guest: 'Omar Hassan', agent: AGENTS[2], adults: 1, children: 1, zone: 'Patong', hotel: 'Novotel Phuket' },
  { guest: 'Chen Wei', agent: AGENTS[1], adults: 2, zone: 'Kata', hotel: 'Kata Palm Resort' },
  { guest: 'Anna Kowalski', agent: AGENTS[0], adults: 1, zone: 'Karon', hotel: 'Beyond Resort Karon' },
  { guest: 'Diego Alvarez', agent: AGENTS[3], adults: 2, infants: 1, zone: 'Patong', hotel: 'ABC Hotel' },
  { guest: 'Priya Iyer', agent: AGENTS[2], adults: 2, zone: 'Other', hotel: 'Laguna Phuket', pending: true },
  { guest: 'Tom Hughes', agent: AGENTS[1], adults: 1, zone: 'Patong', hotel: 'Holiday Inn Resort' },
  { guest: 'Sofia Ricci', agent: AGENTS[0], adults: 2, zone: 'Kata', hotel: 'Boathouse' },
  { guest: 'James Park', agent: AGENTS[3], adults: 2, children: 1, zone: 'Karon', hotel: 'Centara Grand' },
  { guest: 'Fatima Noor', agent: AGENTS[2], adults: 1, zone: 'Patong', hotel: 'Impiana Patong' },
  { guest: 'Lucas Meyer', agent: AGENTS[1], adults: 2, zone: 'Kata', hotel: 'Kata Palm Resort' },
  { guest: 'Yuki Sato', agent: AGENTS[0], adults: 1, zone: 'Karon', hotel: 'Beyond Resort Karon' },
  { guest: 'Nora Lindqvist', agent: AGENTS[3], adults: 2, zone: 'Patong', hotel: 'Novotel Phuket' },
  { guest: 'Raj Malhotra', agent: AGENTS[2], adults: 2, zone: 'Other', hotel: 'The Nai Harn', pending: true },
  { guest: 'Chloe Dubois', agent: AGENTS[1], adults: 1, children: 1, zone: 'Kata', hotel: 'Boathouse' },
  { guest: 'Ben Carter', agent: AGENTS[0], adults: 2, zone: 'Patong', hotel: 'ABC Hotel' },
  { guest: 'Aisha Khan', agent: AGENTS[3], adults: 1, zone: 'Karon', hotel: 'Centara Grand' },
  { guest: 'Marco Rossi', agent: AGENTS[2], adults: 2, zone: 'Patong', hotel: 'Holiday Inn Resort' },
  { guest: 'Helen Cho', agent: AGENTS[1], adults: 2, zone: 'Kata', hotel: 'Kata Palm Resort' },
  { guest: 'Ibrahim Ali', agent: AGENTS[0], adults: 1, zone: 'Karon', hotel: 'Beyond Resort Karon' },
  { guest: 'Grace Kim', agent: AGENTS[3], adults: 8, children: 4, zone: 'Patong', hotel: 'Impiana Patong' },
  { guest: 'Peter Novak', agent: AGENTS[2], adults: 2, zone: 'Kata', hotel: 'Boathouse' },
]

const SEP17_JB_GUESTS: Array<{
  guest: string
  agent: (typeof AGENTS)[number]
  adults: number
  children?: number
  infants?: number
  tourLeaders?: number
  zone: PickupZone['name']
  hotel: string
  canoe: 'Included' | 'Not Included'
}> = [
  { guest: 'Priya Nair', agent: AGENTS[1], adults: 2, zone: 'Kata', hotel: 'Kata Palm Resort', canoe: 'Included' },
  { guest: 'Amit Verma', agent: AGENTS[3], adults: 1, zone: 'Patong', hotel: 'Impiana Patong', canoe: 'Not Included' },
  { guest: 'Sophie Martin', agent: AGENTS[0], adults: 2, children: 1, zone: 'Karon', hotel: 'Centara Grand', canoe: 'Included' },
  { guest: 'Ken Watanabe', agent: AGENTS[2], adults: 1, zone: 'Patong', hotel: 'Novotel Phuket', canoe: 'Included' },
  { guest: 'Lara Costa', agent: AGENTS[1], adults: 2, zone: 'Kata', hotel: 'Boathouse', canoe: 'Not Included' },
  { guest: 'Daniel Lee', agent: AGENTS[0], adults: 2, zone: 'Karon', hotel: 'Beyond Resort Karon', canoe: 'Included' },
  { guest: 'Maya Singh', agent: AGENTS[3], adults: 1, children: 1, zone: 'Patong', hotel: 'ABC Hotel', canoe: 'Included' },
  { guest: 'Oliver Brown', agent: AGENTS[2], adults: 2, tourLeaders: 1, zone: 'Kata', hotel: 'Kata Palm Resort', canoe: 'Included' },
  { guest: 'Ines Dubois', agent: AGENTS[1], adults: 1, zone: 'Karon', hotel: 'Centara Grand', canoe: 'Not Included' },
  { guest: 'Samir Patel', agent: AGENTS[0], adults: 2, zone: 'Patong', hotel: 'Holiday Inn Resort', canoe: 'Included' },
  { guest: 'Nina Volkov', agent: AGENTS[3], adults: 2, infants: 1, zone: 'Kata', hotel: 'Boathouse', canoe: 'Included' },
  { guest: 'Jack Wilson', agent: AGENTS[2], adults: 1, zone: 'Patong', hotel: 'Impiana Patong', canoe: 'Not Included' },
]

function zoneTime(zone: PickupZone['name'], pending?: boolean) {
  if (zone === 'No Transfer') return { pickupTime: 'No transfer', status: 'Confirmed' as const }
  if (pending || zone === 'Other') return { pickupTime: 'Awaiting pickup time', status: 'Pending Pickup Time' as const }
  const match = INITIAL_ZONES.find((item) => item.name === zone)
  return { pickupTime: match?.time ?? '07:30', status: 'Confirmed' as const }
}

const SEP17_PP_BOOKINGS: Booking[] = SEP17_PP_GUESTS.map((row, index) => {
  const meta = zoneTime(row.zone, row.pending)
  return {
    code: `PP2609-${String(index + 1).padStart(4, '0')}`,
    agentSlug: row.agent.slug,
    agentName: row.agent.name,
    agentRef: '',
    program: 'PP' as const,
    date: '2026-09-17',
    parkFee: index % 5 === 0 ? ('Not Included' as const) : ('Included' as const),
    canoe: null,
    adults: row.adults,
    children: row.children ?? 0,
    infants: row.infants ?? 0,
    tourLeaders: 0,
    leadGuest: row.guest,
    pickupZone: row.zone,
    pickupHotel: row.hotel,
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: meta.pickupTime,
    status: meta.status,
  }
})

const SEP17_JB_BOOKINGS: Booking[] = SEP17_JB_GUESTS.map((row, index) => {
  const meta = zoneTime(row.zone)
  return {
    code: `JB2609-${String(index + 1).padStart(4, '0')}`,
    agentSlug: row.agent.slug,
    agentName: row.agent.name,
    agentRef: '',
    program: 'James Bond' as const,
    date: '2026-09-17',
    parkFee: 'Included' as const,
    canoe: row.canoe,
    adults: row.adults,
    children: row.children ?? 0,
    infants: row.infants ?? 0,
    tourLeaders: row.tourLeaders ?? 0,
    leadGuest: row.guest,
    pickupZone: row.zone,
    pickupHotel: row.hotel,
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: meta.pickupTime,
    status: meta.status,
  }
})

const RAW_INITIAL_BOOKINGS: Booking[] = [
  ...SEP17_PP_BOOKINGS,
  ...SEP17_JB_BOOKINGS,
  {
    code: 'PP2609-0001',
    agentSlug: 'mumbai-holidays',
    agentName: 'Mumbai Holidays',
    agentRef: '',
    program: 'PP',
    date: '2026-09-18',
    parkFee: 'Not Included',
    canoe: null,
    adults: 10,
    children: 2,
    infants: 0,
    tourLeaders: 1,
    leadGuest: 'Rahul Mehta',
    pickupZone: 'Karon',
    pickupHotel: 'Centara Grand',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '08:00',
    status: 'Confirmed',
  },
  {
    code: 'JB2609-0002',
    agentSlug: 'delhi-travel',
    agentName: 'Delhi Travel Group',
    agentRef: '',
    program: 'James Bond',
    date: '2026-09-18',
    parkFee: 'Included',
    canoe: 'Not Included',
    adults: 6,
    children: 1,
    infants: 1,
    tourLeaders: 0,
    leadGuest: 'Ananya Sharma',
    pickupZone: 'Patong',
    pickupHotel: 'Holiday Inn Resort',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:30',
    status: 'Confirmed',
  },
  {
    code: 'PP2609-0001',
    agentSlug: 'abc-travel',
    agentName: 'ABC Travel India',
    agentRef: '',
    program: 'PP',
    date: '2026-09-19',
    parkFee: 'Included',
    canoe: null,
    adults: 12,
    children: 4,
    infants: 0,
    tourLeaders: 1,
    leadGuest: 'David Chen',
    pickupZone: 'Other',
    pickupHotel: 'Laguna Phuket',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: 'Awaiting pickup time',
    status: 'Pending Pickup Time',
  },
  {
    code: 'JB2609-0001',
    agentSlug: 'golden-triangle',
    agentName: 'Golden Triangle Travel',
    agentRef: '',
    program: 'James Bond',
    date: '2026-09-20',
    parkFee: 'Included',
    canoe: 'Included',
    adults: 4,
    children: 0,
    infants: 0,
    tourLeaders: 0,
    leadGuest: 'Michael Tan',
    pickupZone: 'Kata',
    pickupHotel: 'The Shore Residences',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:45',
    status: 'Confirmed',
  },
  {
    code: 'PP2608-0001',
    agentSlug: 'abc-travel',
    agentName: 'ABC Travel India',
    agentRef: '',
    program: 'PP',
    date: '2026-08-15',
    parkFee: 'Included',
    canoe: null,
    adults: 6,
    children: 2,
    infants: 0,
    tourLeaders: 1,
    leadGuest: 'Arjun Patel',
    pickupZone: 'Patong',
    pickupHotel: 'Burasari Resort',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:30',
    status: 'Confirmed',
  },
  {
    code: 'JB2608-0001',
    agentSlug: 'golden-triangle',
    agentName: 'Golden Triangle Travel',
    agentRef: '',
    program: 'James Bond',
    date: '2026-08-16',
    parkFee: 'Included',
    canoe: 'Included',
    adults: 4,
    children: 1,
    infants: 0,
    tourLeaders: 0,
    leadGuest: 'Sana Kapoor',
    pickupZone: 'Kata',
    pickupHotel: 'Kata Thani',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:45',
    status: 'Confirmed',
  },
  {
    code: 'PP2608-0001',
    agentSlug: 'mumbai-holidays',
    agentName: 'Mumbai Holidays',
    agentRef: '',
    program: 'PP',
    date: '2026-08-22',
    parkFee: 'Not Included',
    canoe: null,
    adults: 8,
    children: 3,
    infants: 1,
    tourLeaders: 1,
    leadGuest: 'Neha Joshi',
    pickupZone: 'Karon',
    pickupHotel: 'Hilton Phuket Arcadia',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '08:00',
    status: 'Confirmed',
  },
  {
    code: 'JB2608-0001',
    agentSlug: 'delhi-travel',
    agentName: 'Delhi Travel Group',
    agentRef: '',
    program: 'James Bond',
    date: '2026-08-28',
    parkFee: 'Included',
    canoe: 'Not Included',
    adults: 7,
    children: 0,
    infants: 0,
    tourLeaders: 1,
    leadGuest: 'Vikram Singh',
    pickupZone: 'Patong',
    pickupHotel: 'Amari Phuket',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:30',
    status: 'Confirmed',
  },
  {
    code: 'PP2609-0001',
    agentSlug: 'delhi-travel',
    agentName: 'Delhi Travel Group',
    agentRef: '',
    program: 'PP',
    date: '2026-09-05',
    parkFee: 'Included',
    canoe: null,
    adults: 5,
    children: 1,
    infants: 0,
    tourLeaders: 0,
    leadGuest: 'Meera Iyer',
    pickupZone: 'Kata',
    pickupHotel: "Mom Tri's Villa Royale",
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:45',
    status: 'Confirmed',
  },
  {
    code: 'JB2609-0001',
    agentSlug: 'mumbai-holidays',
    agentName: 'Mumbai Holidays',
    agentRef: '',
    program: 'James Bond',
    date: '2026-09-10',
    parkFee: 'Included',
    canoe: 'Included',
    adults: 3,
    children: 2,
    infants: 1,
    tourLeaders: 0,
    leadGuest: 'Karan Malhotra',
    pickupZone: 'Other',
    pickupHotel: 'Trisara Phuket',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: 'Awaiting pickup time',
    status: 'Pending Pickup Time',
  },
  {
    code: 'PP2609-0001',
    agentSlug: 'golden-triangle',
    agentName: 'Golden Triangle Travel',
    agentRef: '',
    program: 'PP',
    date: '2026-09-25',
    parkFee: 'Included',
    canoe: null,
    adults: 9,
    children: 2,
    infants: 0,
    tourLeaders: 1,
    leadGuest: 'Anita Rao',
    pickupZone: 'Patong',
    pickupHotel: 'Indigo Pearl',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:30',
    status: 'Confirmed',
  },
  {
    code: 'JB2609-0001',
    agentSlug: 'abc-travel',
    agentName: 'ABC Travel India',
    agentRef: '',
    program: 'James Bond',
    date: '2026-09-28',
    parkFee: 'Not Included',
    canoe: 'Included',
    adults: 4,
    children: 0,
    infants: 0,
    tourLeaders: 0,
    leadGuest: 'Liam Wright',
    pickupZone: 'Karon',
    pickupHotel: 'Movenpick Resort',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '08:00',
    status: 'Confirmed',
  },
  {
    code: 'PP2610-0001',
    agentSlug: 'abc-travel',
    agentName: 'ABC Travel India',
    agentRef: '',
    program: 'PP',
    date: '2026-10-03',
    parkFee: 'Included',
    canoe: null,
    adults: 11,
    children: 3,
    infants: 1,
    tourLeaders: 1,
    leadGuest: 'Sophie Bennett',
    pickupZone: 'Patong',
    pickupHotel: 'Holiday Inn Resort',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:30',
    status: 'Confirmed',
  },
  {
    code: 'JB2610-0001',
    agentSlug: 'mumbai-holidays',
    agentName: 'Mumbai Holidays',
    agentRef: '',
    program: 'James Bond',
    date: '2026-10-05',
    parkFee: 'Included',
    canoe: 'Included',
    adults: 6,
    children: 1,
    infants: 0,
    tourLeaders: 0,
    leadGuest: 'Ravi Desai',
    pickupZone: 'Kata',
    pickupHotel: 'Sawasdee Village',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:45',
    status: 'Confirmed',
  },
  {
    code: 'PP2610-0001',
    agentSlug: 'delhi-travel',
    agentName: 'Delhi Travel Group',
    agentRef: '',
    program: 'PP',
    date: '2026-10-12',
    parkFee: 'Not Included',
    canoe: null,
    adults: 7,
    children: 2,
    infants: 0,
    tourLeaders: 1,
    leadGuest: 'Ishaan Gupta',
    pickupZone: 'Karon',
    pickupHotel: 'Centara Karon',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '08:00',
    status: 'Confirmed',
  },
  {
    code: 'JB2610-0001',
    agentSlug: 'golden-triangle',
    agentName: 'Golden Triangle Travel',
    agentRef: '',
    program: 'James Bond',
    date: '2026-10-18',
    parkFee: 'Included',
    canoe: 'Not Included',
    adults: 5,
    children: 0,
    infants: 0,
    tourLeaders: 0,
    leadGuest: 'Elena Rossi',
    pickupZone: 'Patong',
    pickupHotel: 'Novotel Phuket',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:30',
    status: 'Confirmed',
  },
  {
    code: 'PP2610-0001',
    agentSlug: 'abc-travel',
    agentName: 'ABC Travel India',
    agentRef: '',
    program: 'PP',
    date: '2026-10-25',
    parkFee: 'Included',
    canoe: null,
    adults: 8,
    children: 1,
    infants: 1,
    tourLeaders: 0,
    leadGuest: 'Hannah Cole',
    pickupZone: 'Other',
    pickupHotel: 'The Nai Harn',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: 'Awaiting pickup time',
    status: 'Pending Pickup Time',
  },
  {
    code: 'PP2611-0001',
    agentSlug: 'mumbai-holidays',
    agentName: 'Mumbai Holidays',
    agentRef: '',
    program: 'PP',
    date: '2026-11-02',
    parkFee: 'Included',
    canoe: null,
    adults: 10,
    children: 4,
    infants: 0,
    tourLeaders: 1,
    leadGuest: 'Aisha Khan',
    pickupZone: 'Patong',
    pickupHotel: 'Baan Yin Dee',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:30',
    status: 'Confirmed',
  },
  {
    code: 'JB2611-0001',
    agentSlug: 'delhi-travel',
    agentName: 'Delhi Travel Group',
    agentRef: '',
    program: 'James Bond',
    date: '2026-11-08',
    parkFee: 'Included',
    canoe: 'Included',
    adults: 4,
    children: 2,
    infants: 0,
    tourLeaders: 0,
    leadGuest: 'Rohan Mehta',
    pickupZone: 'Kata',
    pickupHotel: 'Boathouse',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:45',
    status: 'Confirmed',
  },
  {
    code: 'PP2611-0001',
    agentSlug: 'golden-triangle',
    agentName: 'Golden Triangle Travel',
    agentRef: '',
    program: 'PP',
    date: '2026-11-15',
    parkFee: 'Not Included',
    canoe: null,
    adults: 6,
    children: 0,
    infants: 0,
    tourLeaders: 1,
    leadGuest: 'Claire Dubois',
    pickupZone: 'Karon',
    pickupHotel: 'Beyond Resort Karon',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '08:00',
    status: 'Confirmed',
  },
  {
    code: 'JB2611-0001',
    agentSlug: 'abc-travel',
    agentName: 'ABC Travel India',
    agentRef: '',
    program: 'James Bond',
    date: '2026-11-22',
    parkFee: 'Included',
    canoe: 'Included',
    adults: 8,
    children: 3,
    infants: 1,
    tourLeaders: 0,
    leadGuest: 'Tom Hughes',
    pickupZone: 'Patong',
    pickupHotel: 'Impiana Patong',
    roomNumber: '',
    note: '',
    transferExtraCharge: '',
    pickupTime: '07:30',
    status: 'Confirmed',
  },
]

/** Assign PP2609-0001 style codes sequentially per program + month. */
function withSequentialCodes(bookings: Booking[]): Booking[] {
  const counters = new Map<string, number>()
  return bookings.map((booking) => {
    const stem = bookingCodeStem(booking.program, booking.date)
    const next = (counters.get(stem) ?? 0) + 1
    counters.set(stem, next)
    return { ...booking, code: `${stem}${String(next).padStart(4, '0')}` }
  })
}

export const INITIAL_BOOKINGS: Booking[] = withSequentialCodes(RAW_INITIAL_BOOKINGS)

export function mergeBookings(stored: Booking[], seed: Booking[]) {
  const existing = new Set(stored.map((booking) => booking.code))
  return [...stored, ...seed.filter((booking) => !existing.has(booking.code))].map((booking) => ({
    ...booking,
    agentRef: booking.agentRef ?? '',
    roomNumber: booking.roomNumber ?? '',
    note: booking.note ?? '',
  }))
}

/** Empty = every day uses DEFAULT_PP_CAPACITY / DEFAULT_JB_CAPACITY until admin overrides. */
export const INITIAL_AVAILABILITY: Availability[] = []

export function getAgentBySlug(slug: string) {
  return AGENTS.find((agent) => agent.slug === slug)
}
